set -e

EXE="./cryptid"
CMD_FILE="./cmd/cryptid.go"
NO_CLIPBOARD_FLAG="--no-clipboard"

go build -o $EXE $CMD_FILE

# >>> Password Complex <<<
LENGTH_OF_COMPLEX_PASSWORD=24
COMPLEX_PASSWORD_COMMAND="$($EXE password complex -l $LENGTH_OF_COMPLEX_PASSWORD $NO_CLIPBOARD_FLAG)"

# make sure the password has the correct length
if [ ${#COMPLEX_PASSWORD_COMMAND} -ne $LENGTH_OF_COMPLEX_PASSWORD ]; then
    echo "Error: The length of the password generated by the complex command is not $LENGTH_OF_COMPLEX_PASSWORD"
    exit 1
fi
# >>> Password Complex <<<


# >>> Password Passphrase <<<
COUNT_OF_WORDS=5
SEPERATOR="_"
PASSPHRASE_PASSWORD_COMMAND="$($EXE password passphrase -c $COUNT_OF_WORDS -s $SEPERATOR $NO_CLIPBOARD_FLAG)"
# make sure the number of seperators is equal to the count of words minus 1
if [ $(echo $PASSPHRASE_PASSWORD_COMMAND | grep -o $SEPERATOR | wc -l) -ne $((COUNT_OF_WORDS - 1)) ]; then
    echo "Error: The number of seperators in the password generated by the passphrase command is not equal to the count of words minus 1"
    exit 1
fi
# >>> Password Passphrase <<<


# >>> JWT SECRET <<<
JWT_256_SECRET_COMMAND="$($EXE jwt hs256 $NO_CLIPBOARD_FLAG)"
if [ ${#JWT_256_SECRET_COMMAND} -ne 32 ]; then
    echo "Error: The length of the JWT keys generated by the hs256 command is not 64"
    exit 1
fi

JWT_384_SECRET="$($EXE jwt hs384 $NO_CLIPBOARD_FLAG)"
if [ ${#JWT_384_SECRET} -ne 48 ]; then
    echo "Error: The length of the JWT keys generated by the hs384 command is not 96"
    exit 1
fi

JWT_512_SECRET="$($EXE jwt hs512 $NO_CLIPBOARD_FLAG)"
if [ ${#JWT_512_SECRET} -ne 64 ]; then
    echo "Error: The length of the JWT keys generated by the hs512 command is not 128"
    exit 1
fi
# >>> JWT SECRET <<<

ENC_WORDS_FILE="./internal/commands/password/words.enc"
WORDS_FILE="./internal/commands/password/words.txt"

# >>> AES ENCRYPT <<<
AES_KEY="123"

AES_ENCRYPT_COMMAND="$($EXE aes encrypt -i $WORDS_FILE -o $ENC_WORDS_FILE -p $AES_KEY)"
ls ./internal/commands/password

# make sure the file is created
if [ ! -f $ENC_WORDS_FILE ]; then
    echo "Error: The file $ENC_WORDS_FILE is not created"
    exit 1
fi

# make sure the file is not empty
if [ ! -s $ENC_WORDS_FILE ]; then
    echo "Error: The file $ENC_WORDS_FILE is empty"
    exit 1
fi
# >>> AES ENCRYPT <<<

# >>> AES DECRYPT <<<
AES_DECRYPT_COMMAND="$($EXE aes decrypt -i $ENC_WORDS_FILE -o $WORDS_FILE -p $AES_KEY)"
# make sure the file is created
if [ ! -f $WORDS_FILE ]; then
    echo "Error: The file $WORDS_FILE is not created"
    exit 1
fi

# make sure the file is not empty
if [ ! -s $WORDS_FILE ]; then
    echo "Error: The file $WORDS_FILE is empty"
    exit 1
fi
# >>> AES DECRYPT <<<