/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EncryptImport } from './routes/encrypt'
import { Route as DecryptImport } from './routes/decrypt'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const EncryptRoute = EncryptImport.update({
  id: '/encrypt',
  path: '/encrypt',
  getParentRoute: () => rootRoute,
} as any)

const DecryptRoute = DecryptImport.update({
  id: '/decrypt',
  path: '/decrypt',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/decrypt': {
      id: '/decrypt'
      path: '/decrypt'
      fullPath: '/decrypt'
      preLoaderRoute: typeof DecryptImport
      parentRoute: typeof rootRoute
    }
    '/encrypt': {
      id: '/encrypt'
      path: '/encrypt'
      fullPath: '/encrypt'
      preLoaderRoute: typeof EncryptImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decrypt' | '/encrypt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decrypt' | '/encrypt'
  id: '__root__' | '/' | '/decrypt' | '/encrypt'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecryptRoute: typeof DecryptRoute
  EncryptRoute: typeof EncryptRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecryptRoute: DecryptRoute,
  EncryptRoute: EncryptRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/decrypt",
        "/encrypt"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/decrypt": {
      "filePath": "decrypt.tsx"
    },
    "/encrypt": {
      "filePath": "encrypt.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
