name: Build

on:
  push:
    tags:
      - '*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli:
    permissions: 
      contents: write
    runs-on: ubuntu-22.04
    env:
      GO_VERSION: ${{ vars.GO_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: "**/*.sum"
          go-version: ${{ env.GO_VERSION }}

      - name: Build CLI
        run: make build-cli VERSION=${{ github.ref_name }}

      # get the tar.gz files from the dist directory and upload them to the release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*.tar.gz