name: Build

on:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      GO_VERSION: ${{ vars.GO_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: "**/*.sum"
          go-version: ${{ env.GO_VERSION }}

      - name: Build CLI
        run: make build-cli VERSION=${{ github.ref_name }}

      # get the tar.gz files from the dist directory and upload them to the release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: dist/*.tar.gz

  build-bash-completion:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      RUBY_VERSION: ${{ vars.RUBY_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install completely
        run: gem install completely

      - name: Generate bash completion
        run: completely generate && mv completely.bash hyde_completion.bash

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: hyde_completion.bash
