name: Release

on:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      GO_VERSION: ${{ vars.GO_VERSION }}
      RUBY_VERSION: ${{ vars.RUBY_VERSION }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5.4.0
        with:
          cache-dependency-path: "**/*.sum"
          go-version: ${{ env.GO_VERSION }}

      - name: Build CLI
        run: make build-cli-bulk

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.232.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }} 

      - name: Install completely
        run: gem install completely

      - name: Generate Bash Completion
        run: |
          mkdir -p dist
          completely generate
          cp ./completely.bash dist/hyde_completion.bash

      # get the tar.gz files from the dist directory and upload them to the release
      - name: Release CLI
        uses: softprops/action-gh-release@v2.2.1
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: |
            dist/*

  build-and-publish-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: write # Required to publish to GitHub Packages
      contents: read # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
